In [13]:
# Import Dependencies
import pandas as pd
import numpy as np

I converted the original excel file into a csv file but looks like it can't be coverted to DataFrame.

In [14]:
df = pd.read_csv("CensusProfile2016.csv")
df

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 89640: invalid start byte

The raw excel file then cleaned to keep only the ethnic origin based on the continent and then saved as a CSV file. The CSV file was importd and converted to DataFrame for analysis. The data can be filtered further based on the ML model selection.

In [15]:
df = pd.read_csv("Ethnic origin data (Cencus 2016).csv")
df

,Unnamed: 0,Toronto,Ward 1,Ward 2,Ward 3,Ward 4,Ward 5,Ward 6,Ward 7,Ward 8,...,Ward 39,Ward 40,Ward 41,Ward 42,Ward 43,Ward 44,Etobicoke York,North York,Scarborough,Toronto and East York
0,Total - Ethnic origin for the population in pr...,2691665,60040,56295,52470,55395,69645,66690,52905,49850,...,53015,63700,65100,76250,54305,60005,635615,684985,623375,747685
1,North American Aboriginal origins,35630,330,355,590,500,830,1520,310,440,...,135,440,120,435,1120,775,7755,5335,7070,15465
2,Other North American origins,345705,4390,5410,7355,6270,10340,12285,4150,3900,...,2585,5215,2855,5935,7865,8860,76950,70255,67345,131165
3,European origins,1288850,10095,21600,36855,37965,49005,45985,16315,11815,...,6520,15595,6280,9245,19230,25050,352370,293410,167410,475665
4,Caribbean origins,165735,7895,5525,1725,2925,2110,3045,6900,7440,...,1945,4180,2885,10680,6830,7785,51390,33290,53255,27795
5,"Latin, Central and South American origins",113820,3730,3995,1800,2780,2385,2505,6470,4535,...,515,1765,890,3180,2240,2740,41575,26915,19330,26000
6,African origins,146870,7740,8635,2080,3205,2365,2455,4775,6725,...,1920,2715,1050,4355,3950,3300,48500,33530,31500,33335
7,Asian origins,1079290,32640,19305,11115,10100,15075,13585,20450,21575,...,43155,41840,55720,53785,24725,25320,165345,325245,372870,215835
8,Oceania origins,5795,15,45,65,125,140,190,10,20,...,20,65,0,55,85,65,1060,1090,645,2995