# Optimization hyperparameter

In [1]:
# Import dependencies 
import pandas as pd
import os
import matplotlib.pyplot as plt

In [10]:
# import dependencies
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
# Import encoded datafram
encoded_df3 = pd.read_csv('encoded_df3.csv')
encoded_df3

        state_beer              style  availability   abv  types  taste
0               36  German Hefeweizen             2   5.0      4   4.50
1               36  German Hefeweizen             6   5.6      2   4.50
2               43  German Hefeweizen             6   5.4      1   4.00
3               37  German Hefeweizen             4   5.0     10   4.25
4               46  German Hefeweizen             2   4.5      3   4.00
...            ...                ...           ...   ...    ...    ...
443995           4              Stout             6   5.8      3   4.50
443996          10              Stout             2   8.0      2   3.50
443997           4              Stout             2  11.0     10   5.00
443998          22              Stout             2  13.1      5   4.75
443999          15              Stout             6  10.0      1   4.50

[444000 rows x 6 columns]

In [3]:
#encode string values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
encoded_df4 = encoded_df3.copy()
encoded_df4['style'] = le.fit_transform(encoded_df4['style'])
encoded_df4

        state_beer  style  availability   abv  types  taste
0               36     18             2   5.0      4   4.50
1               36     18             6   5.6      2   4.50
2               43     18             6   5.4      1   4.00
3               37     18             4   5.0     10   4.25
4               46     18             2   4.5      3   4.00
...            ...    ...           ...   ...    ...    ...
443995           4     36             6   5.8      3   4.50
443996          10     36             2   8.0      2   3.50
443997           4     36             2  11.0     10   5.00
443998          22     36             2  13.1      5   4.75
443999          15     36             6  10.0      1   4.50

[444000 rows x 6 columns]

In [40]:
# Define the target set
y = encoded_df3["style"].values
y

array(['German Hefeweizen', 'German Hefeweizen', 'German Hefeweizen', ...,
       'Stout', 'Stout', 'Stout'], dtype=object)

In [18]:
#define the features set
X = encoded_df3.copy()
X = X.drop(columns =["style"])
X

        state_beer  availability   abv  types  taste
0               36             2   5.0      4   4.50
1               36             6   5.6      2   4.50
2               43             6   5.4      1   4.00
3               37             4   5.0     10   4.25
4               46             2   4.5      3   4.00
...            ...           ...   ...    ...    ...
443995           4             6   5.8      3   4.50
443996          10             2   8.0      2   3.50
443997           4             2  11.0     10   5.00
443998          22             2  13.1      5   4.75
443999          15             6  10.0      1   4.50

[444000 rows x 5 columns]

In [41]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [42]:
# Create a StandardScaler instance
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [43]:
# Create a random forest classifier
xgb_model = XGBClassifier()
# fit the model
xgb_model = xgb_model.fit(X_train_scaled, y_train)

/Users/alexzzf/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[09:43:51] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [44]:
# make predictions for test data
predictions = xgb_model.predict(X_test_scaled)

In [45]:
#calculate matrix and accuracy score
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(cm)
acc_score = accuracy_score(y_test, predictions)

In [46]:
display(cm_df)

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,2675,1,19,3,3,19,31,74,21,7,...,19,6,22,29,2,60,7,1,38,1
1,2,2907,10,207,74,0,0,0,3,41,...,14,5,1,1,24,5,123,62,22,6
2,4,1,2947,12,41,3,6,2,2,33,...,28,11,15,55,40,5,10,20,73,19
3,5,89,2,3157,47,3,0,0,2,5,...,6,1,0,1,16,5,76,37,5,1
4,12,50,34,59,2996,4,1,1,8,37,...,28,8,9,11,26,2,28,51,17,4
5,55,4,13,2,23,2319,47,66,79,5,...,18,4,18,36,2,8,2,0,50,9
6,34,0,4,0,0,14,2950,37,9,3,...,6,0,3,12,1,18,0,0,101,0
7,75,0,30,0,4,113,99,2145,50,32,...,21,35,27,29,6,27,3,3,65,4
8,77,15,66,17,17,27,38,62,2087,28,...,80,20,29,34,22,26,61,44,71,42
9,11,66,106,74,175,37,64,36,33,1985,...,56,35,15,52,78,19,55,71,93,66
10,50,0,13,0,5,10,34,18,30,3,...,71,3,33,45,3,20,14,4,32,13
11,0,51,22,28,64,9,2,2,24,22,...,1,1,2,0,39,0,19,18,17,11
12,52,2,105,5,55,37,77,60,41,69,...,54,24,20,57,23,33,11,12,425,9
13,7,2,69,0,11,2,20,5,7,11,...,9,6,7,31,5,22,1,13,88,1
14,38,3,31,5,29,46,77,88,20,31,...,23,45,13,24,11,13,13,15,57,30
15,31,1,19,0,4,11,13,58,39,10,...,18,14,34,22,0,18,1,8,47,4
16,9,0,16,0,6,8,0,4,4,6,...,14,13,9,23,8,17,0,7,22,24
17,8,11,52,12,62,2,0,6,7,20,...,10,1,6,6,35,4,20,22,32,55
18,50,0,6,0,1,93,38,120,40,6,...,41,5,19,32,42,24,1,0,27,0
19,33,0,7,0,0,20,65,70,10,3,...,26,0,29,6,0,13,0,0,19,2
20,88,0,0,0,0,84,62,108,33,4,...,15,6,18,12,0,16,0,0,29,2
21,6,1,20,2,11,3,1,7,3,3,...,15,2,7,18,4,7,2,4,30,10
22,11,0,3,0,0,7,7,2,27,4,...,8,109,3,11,1,1,3,0,12,3
23,21,1,32,1,3,22,34,33,24,5,...,12,4,19,43,10,28,0,1,18,5
24,13,4,27,6,7,18,14,39,15,20,...,5,11,10,13,27,14,10,7,43,40
25,110,8,18,0,2,58,52,62,58,15,...,14,9,24,12,4,74,9,9,34,7
26,21,0,7,5,0,29,366,59,19,1,...,13,1,4,5,2,8,1,1,65,0
27,42,121,144,23,90,64,59,41,27,45,...,35,21,69,28,32,31,39,49,179,49
28,29,42,134,21,158,47,45,61,58,108,...,138,28,82,84,58,41,71,48,177,44
29,79,5,26,1,28,37,60,84,58,14,...,31,3,20,24,8,46,2,3,71,4
30,66,36,61,33,74,32,12,37,75,47,...,1941,21,69,51,40,34,81,33,129,31
31,6,8,10,1,7,1,5,12,3,3,...,6,3271,7,10,14,1,25,4,10,5
32,88,23,49,9,40,66,16,84,96,64,...,91,34,1685,48,28,27,24,36,157,48
33,35,16,20,12,35,28,25,11,19,18,...,35,15,17,2660,16,31,4,7,79,28
34,4,41,72,40,123,2,2,1,7,56,...,24,17,9,17,2861,20,32,36,26,20
35,13,11,27,0,8,5,29,25,16,5,...,38,3,19,24,19,3007,1,5,33,17
36,22,181,42,99,123,14,14,17,34,84,...,99,30,53,79,44,25,1906,86,80,46
37,5,103,37,60,88,0,0,0,12,22,...,34,9,6,11,30,3,60,2778,51,17
38,24,28,74,17,57,30,145,30,19,61,...,37,17,15,63,15,34,24,42,2133,14
39,6,14,7,1,8,5,6,5,7,12,...,10,12,0,10,9,6,7,9,9,3445

In [47]:
# Display results
print("Confusion Matrix")
print(f"Accuracy Score: {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix
Accuracy Score: 0.7102306852306852
Classification Report
                                             precision    recall  f1-score   support

                         American Cream Ale       0.68      0.73      0.71      3651
                                 Barleywine       0.76      0.79      0.77      3689
                             Belgian Dubbel       0.67      0.80      0.73      3668
                   Belgian Quadrupel (Quad)       0.81      0.87      0.84      3638
                             Belgian Tripel       0.67      0.84      0.74      3584
                            Belgian Witbier       0.70      0.63      0.66      3683
                            Berliner Weisse       0.65      0.80      0.72      3681
                                 Blonde Ale       0.60      0.58      0.59      3685
                                  Brown Ale       0.67      0.57      0.61      3671
                                   Dark Ale       0.67      0.53      0.59      3747
English Extra Special / Strong Bitter (ESB)       0.69      0.77      0.73      3637
                            English Old Ale       0.82      0.87      0.84      3610
                              Farmhouse Ale       0.52      0.45      0.48      3701
                      French BiÃ¨re de Garde       0.77      0.84      0.80      3724
                       Fruit and Field Beer       0.75      0.62      0.68      3687
                             German Altbier       0.79      0.80      0.79      3593
                                German Bock       0.84      0.89      0.86      3641
                          German Doppelbock       0.73      0.84      0.79      3652
                          German Hefeweizen       0.66      0.61      0.63      3619
                              German Helles       0.62      0.80      0.70      3661
                              German KÃ¶lsch       0.60      0.67      0.63      3632
                             German Maibock       0.81      0.89      0.85      3650
                German MÃ¤rzen / Oktoberfest       0.87      0.90      0.88      3728
                         German Schwarzbier       0.76      0.79      0.77      3632
                        Herb and Spice Beer       0.78      0.79      0.79      3717
                                      Lager       0.75      0.62      0.67      3628
                               Leipzig Gose       0.70      0.76      0.73      3707
                                      Other       0.71      0.46      0.56      3673
                                   Pale Ale       0.48      0.33      0.39      3692
                                    Pilsner       0.60      0.58      0.59      3626
                                     Porter       0.62      0.53      0.57      3657
                               Pumpkin Beer       0.85      0.89      0.87      3660
                                    Red Ale       0.69      0.46      0.55      3675
                                   Rye Beer       0.71      0.73      0.72      3657
                     Scotch Ale / Wee Heavy       0.79      0.79      0.79      3640
                               Scottish Ale       0.79      0.82      0.81      3645
                                      Stout       0.69      0.52      0.59      3695
                                 Strong Ale       0.78      0.77      0.78      3605
                                   Wild Ale       0.46      0.58      0.51      3669
                              Winter Warmer       0.83      0.93      0.88      3710

                                   accuracy                           0.71    146520
                                  macro avg       0.71      0.71      0.71    146520
                               weighted avg       0.71      0.71      0.71    146520

In [48]:
# calculate feature importance in the Random Forest model
importances = xgb_model.feature_importances_
importances

array([0.189438  , 0.2811871 , 0.2896496 , 0.18110017, 0.05862512],
      dtype=float32)

In [49]:
# Sort the features by importances
sorted(zip(xgb_model.feature_importances_, encoded_df3.columns), reverse = True)

[(0.2896496, 'availability'),
 (0.2811871, 'style'),
 (0.189438, 'state_beer'),
 (0.18110017, 'abv'),
 (0.058625124, 'types')]

# Pruner for XGBoost